<?php
// Acces compte mysql sur isis.

$server = "localhost";
$user = "root";
$password = "Iutphoto123@";
$base = "BDD";

// Pour l'utiliser mettre par exemple dans votre .php qui ouvre votre base :
//   include("/users/etudiant/a/am103879/www/.ht_mysql.inc");
//   mysql_connect("$server","$user","$password") or die("Pb connexion MySQL");
//   mysql_select_db("$base") or die("Pb selection base");
?>
